import { createContext, useContext, useState, ReactNode, useEffect } from "react";

export type Language = "en" | "es" | "de" | "bn" | "hi" | "ur" | "te" | "fr";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Header
    "app.title": "Nexus Pro",
    "app.subtitle": "Enterprise Thinking Engine",
    "button.newSession": "New Session",
    "button.login": "Login",
    "button.logout": "Logout",
    "menu.account": "Account",
    "menu.settings": "Settings",
    
    // Empty State
    "empty.greeting": "Good Afternoon, Nexus here to help you",
    "empty.disclaimer": "Nexus can make mistakes. Please verify critical information.",
    
    // Input
    "input.placeholder": "Message Nexus...",
    "input.webSearch": "Ask anything - I'll search the web...",
    
    // Attachments
    "attach.camera": "Camera",
    "attach.photo": "Photo",
    "attach.files": "Files",
    "attach.webSearch": "Web Search",
    "attach.enabled": "Enabled",
    "attach.searchInternet": "Search the internet",
    "upload.uploading": "Uploading...",
    
    // Messages
    "message.you": "You",
    "message.ai": "Nexus AI",
    "message.thinking": "Thinking...",
    "message.thinkingProcess": "Thinking Process",
    "message.readAloud": "Read Aloud",
    "message.stop": "Stop",
    "message.generatedWith": "Generated with",
    "message.mode": "mode",
    
    // Voice Settings
    "voice.settings": "Voice Settings",
    "voice.voice": "Voice",
    "voice.speed": "Speed",
    
    // Web Search
    "webSearch.active": "Web Search Active - Nexus will search the internet",
    "webSearch.on": "Web Search ON",
    "webSearch.off": "Web Search",
    
    // Sidebar
    "sidebar.home": "Home",
    "sidebar.reasoningEngine": "Reasoning Engine",
    "sidebar.preferences": "Preferences",
    "sidebar.account": "Account",
    "sidebar.settings": "Settings",
    "sidebar.loginGoogle": "Login with Google",
    "sidebar.yourChats": "Your Chats",
    "sidebar.newChat": "New Chat",
    "sidebar.noChats": "No conversations yet",
    "sidebar.deleteChat": "Delete",
    
    // Modes
    "mode.whatIf": "What If",
    "mode.whatIfDesc": "Hypothetical exploration",
    "mode.chainReaction": "Chain Reaction",
    "mode.chainReactionDesc": "Causal analysis",
    "mode.parallelTimelines": "Parallel Timelines",
    "mode.parallelTimelinesDesc": "Divergent outcomes",
    "mode.active": "Active",
    "mode.selectMode": "Select reasoning mode",
    
    // Account Page
    "account.title": "Account",
    "account.profileInfo": "Profile Information",
    "account.manageProfile": "Manage your profile and preferences",
    "account.notLoggedIn": "Not Logged In",
    "account.loginToAccess": "Login to access your account settings and preferences",
    "account.username": "Username",
    "account.chooseDisplayName": "Choose a display name",
    "account.email": "Email Address",
    "account.managedByGoogle": "Managed by Google",
    "account.saveUsername": "Save Username",
    "account.saving": "Saving...",
    "account.billing": "Billing",
    "account.manageBilling": "Manage your subscription and payment methods",
    "account.freePlan": "Free Plan",
    "account.basicAccess": "Basic access to Nexus features",
    "account.upgradePro": "Upgrade to Pro",
    
    // Language
    "language.select": "Language",
  },
  
  es: {
    "app.title": "Nexus Pro",
    "app.subtitle": "Motor de Pensamiento Empresarial",
    "button.newSession": "Nueva Sesión",
    "button.login": "Iniciar Sesión",
    "button.logout": "Cerrar Sesión",
    "menu.account": "Cuenta",
    "menu.settings": "Configuración",
    "empty.greeting": "Buenas tardes, Nexus está aquí para ayudarte",
    "empty.disclaimer": "Nexus puede cometer errores. Por favor verifica la información crítica.",
    "input.placeholder": "Mensaje a Nexus...",
    "input.webSearch": "Pregunta lo que sea - Buscaré en la web...",
    "attach.camera": "Cámara",
    "attach.photo": "Foto",
    "attach.files": "Archivos",
    "attach.webSearch": "Búsqueda Web",
    "attach.enabled": "Activado",
    "attach.searchInternet": "Buscar en internet",
    "upload.uploading": "Subiendo...",
    "message.you": "Tú",
    "message.ai": "Nexus IA",
    "message.thinking": "Pensando...",
    "message.thinkingProcess": "Proceso de Pensamiento",
    "message.readAloud": "Leer en Voz Alta",
    "message.stop": "Detener",
    "message.generatedWith": "Generado con",
    "message.mode": "modo",
    "voice.settings": "Configuración de Voz",
    "voice.voice": "Voz",
    "voice.speed": "Velocidad",
    "webSearch.active": "Búsqueda Web Activa - Nexus buscará en internet",
    "webSearch.on": "Búsqueda Web ON",
    "webSearch.off": "Búsqueda Web",
    "sidebar.home": "Inicio",
    "sidebar.reasoningEngine": "Motor de Razonamiento",
    "sidebar.preferences": "Preferencias",
    "sidebar.account": "Cuenta",
    "sidebar.settings": "Configuración",
    "sidebar.loginGoogle": "Iniciar con Google",
    "sidebar.yourChats": "Tus Chats",
    "sidebar.newChat": "Nuevo Chat",
    "sidebar.noChats": "Aún no hay conversaciones",
    "sidebar.deleteChat": "Eliminar",
    "mode.whatIf": "¿Qué Pasaría Si?",
    "mode.whatIfDesc": "Exploración hipotética",
    "mode.chainReaction": "Reacción en Cadena",
    "mode.chainReactionDesc": "Análisis causal",
    "mode.parallelTimelines": "Líneas de Tiempo Paralelas",
    "mode.parallelTimelinesDesc": "Resultados divergentes",
    "mode.active": "Activo",
    "mode.selectMode": "Seleccionar modo de razonamiento",
    "account.title": "Cuenta",
    "account.profileInfo": "Información del Perfil",
    "account.manageProfile": "Administra tu perfil y preferencias",
    "account.notLoggedIn": "No has iniciado sesión",
    "account.loginToAccess": "Inicia sesión para acceder a tu configuración",
    "account.username": "Nombre de usuario",
    "account.chooseDisplayName": "Elige un nombre para mostrar",
    "account.email": "Correo Electrónico",
    "account.managedByGoogle": "Administrado por Google",
    "account.saveUsername": "Guardar Nombre",
    "account.saving": "Guardando...",
    "account.billing": "Facturación",
    "account.manageBilling": "Administra tu suscripción y métodos de pago",
    "account.freePlan": "Plan Gratuito",
    "account.basicAccess": "Acceso básico a funciones de Nexus",
    "account.upgradePro": "Actualizar a Pro",
    "language.select": "Idioma",
  },
  
  de: {
    "app.title": "Nexus Pro",
    "app.subtitle": "Enterprise Denk-Engine",
    "button.newSession": "Neue Sitzung",
    "button.login": "Anmelden",
    "button.logout": "Abmelden",
    "menu.account": "Konto",
    "menu.settings": "Einstellungen",
    "empty.greeting": "Guten Tag, Nexus ist hier um dir zu helfen",
    "empty.disclaimer": "Nexus kann Fehler machen. Bitte überprüfe kritische Informationen.",
    "input.placeholder": "Nachricht an Nexus...",
    "input.webSearch": "Frag alles - Ich durchsuche das Web...",
    "attach.camera": "Kamera",
    "attach.photo": "Foto",
    "attach.files": "Dateien",
    "attach.webSearch": "Websuche",
    "attach.enabled": "Aktiviert",
    "attach.searchInternet": "Internet durchsuchen",
    "upload.uploading": "Hochladen...",
    "message.you": "Du",
    "message.ai": "Nexus KI",
    "message.thinking": "Denkt nach...",
    "message.thinkingProcess": "Denkprozess",
    "message.readAloud": "Vorlesen",
    "message.stop": "Stopp",
    "message.generatedWith": "Generiert mit",
    "message.mode": "Modus",
    "voice.settings": "Spracheinstellungen",
    "voice.voice": "Stimme",
    "voice.speed": "Geschwindigkeit",
    "webSearch.active": "Websuche Aktiv - Nexus durchsucht das Internet",
    "webSearch.on": "Websuche AN",
    "webSearch.off": "Websuche",
    "sidebar.home": "Startseite",
    "sidebar.reasoningEngine": "Denk-Engine",
    "sidebar.preferences": "Einstellungen",
    "sidebar.account": "Konto",
    "sidebar.settings": "Einstellungen",
    "sidebar.loginGoogle": "Mit Google anmelden",
    "sidebar.yourChats": "Deine Chats",
    "sidebar.newChat": "Neuer Chat",
    "sidebar.noChats": "Noch keine Gespräche",
    "sidebar.deleteChat": "Löschen",
    "mode.whatIf": "Was Wäre Wenn",
    "mode.whatIfDesc": "Hypothetische Erkundung",
    "mode.chainReaction": "Kettenreaktion",
    "mode.chainReactionDesc": "Kausalanalyse",
    "mode.parallelTimelines": "Parallele Zeitlinien",
    "mode.parallelTimelinesDesc": "Divergente Ergebnisse",
    "mode.active": "Aktiv",
    "mode.selectMode": "Denkmodus auswählen",
    "account.title": "Konto",
    "account.profileInfo": "Profilinformationen",
    "account.manageProfile": "Verwalte dein Profil und Einstellungen",
    "account.notLoggedIn": "Nicht angemeldet",
    "account.loginToAccess": "Melde dich an für Kontoeinstellungen",
    "account.username": "Benutzername",
    "account.chooseDisplayName": "Wähle einen Anzeigenamen",
    "account.email": "E-Mail-Adresse",
    "account.managedByGoogle": "Verwaltet von Google",
    "account.saveUsername": "Benutzername speichern",
    "account.saving": "Speichern...",
    "account.billing": "Abrechnung",
    "account.manageBilling": "Verwalte dein Abo und Zahlungsmethoden",
    "account.freePlan": "Kostenloser Plan",
    "account.basicAccess": "Basis-Zugang zu Nexus-Funktionen",
    "account.upgradePro": "Auf Pro upgraden",
    "language.select": "Sprache",
  },
  
  bn: {
    "app.title": "নেক্সাস প্রো",
    "app.subtitle": "এন্টারপ্রাইজ থিংকিং ইঞ্জিন",
    "button.newSession": "নতুন সেশন",
    "button.login": "লগইন",
    "button.logout": "লগআউট",
    "menu.account": "অ্যাকাউন্ট",
    "menu.settings": "সেটিংস",
    "empty.greeting": "শুভ বিকেল, নেক্সাস তোমাকে সাহায্য করতে এসেছে",
    "empty.disclaimer": "নেক্সাস ভুল করতে পারে। অনুগ্রহ করে গুরুত্বপূর্ণ তথ্য যাচাই করুন।",
    "input.placeholder": "নেক্সাসকে বার্তা দিন...",
    "input.webSearch": "যেকোনো কিছু জিজ্ঞাসা করুন - আমি ওয়েবে খুঁজব...",
    "attach.camera": "ক্যামেরা",
    "attach.photo": "ছবি",
    "attach.files": "ফাইল",
    "attach.webSearch": "ওয়েব সার্চ",
    "attach.enabled": "সক্রিয়",
    "attach.searchInternet": "ইন্টারনেটে খুঁজুন",
    "upload.uploading": "আপলোড হচ্ছে...",
    "message.you": "আপনি",
    "message.ai": "নেক্সাস এআই",
    "message.thinking": "চিন্তা করছি...",
    "message.thinkingProcess": "চিন্তা প্রক্রিয়া",
    "message.readAloud": "জোরে পড়ুন",
    "message.stop": "থামুন",
    "message.generatedWith": "দিয়ে তৈরি",
    "message.mode": "মোড",
    "voice.settings": "ভয়েস সেটিংস",
    "voice.voice": "ভয়েস",
    "voice.speed": "গতি",
    "webSearch.active": "ওয়েব সার্চ সক্রিয় - নেক্সাস ইন্টারনেটে খুঁজবে",
    "webSearch.on": "ওয়েব সার্চ চালু",
    "webSearch.off": "ওয়েব সার্চ",
    "sidebar.home": "হোম",
    "sidebar.reasoningEngine": "রিজনিং ইঞ্জিন",
    "sidebar.preferences": "পছন্দসমূহ",
    "sidebar.account": "অ্যাকাউন্ট",
    "sidebar.settings": "সেটিংস",
    "sidebar.loginGoogle": "গুগল দিয়ে লগইন",
    "sidebar.yourChats": "আপনার চ্যাটস",
    "sidebar.newChat": "নতুন চ্যাট",
    "sidebar.noChats": "এখনও কোনো কথোপকথন নেই",
    "sidebar.deleteChat": "মুছে ফেলুন",
    "mode.whatIf": "যদি হতো",
    "mode.whatIfDesc": "অনুমানমূলক অন্বেষণ",
    "mode.chainReaction": "চেইন রিঅ্যাকশন",
    "mode.chainReactionDesc": "কারণ বিশ্লেষণ",
    "mode.parallelTimelines": "সমান্তরাল টাইমলাইন",
    "mode.parallelTimelinesDesc": "বিভিন্ন ফলাফল",
    "mode.active": "সক্রিয়",
    "mode.selectMode": "রিজনিং মোড নির্বাচন করুন",
    "account.title": "অ্যাকাউন্ট",
    "account.profileInfo": "প্রোফাইল তথ্য",
    "account.manageProfile": "আপনার প্রোফাইল এবং পছন্দ পরিচালনা করুন",
    "account.notLoggedIn": "লগইন করা হয়নি",
    "account.loginToAccess": "অ্যাকাউন্ট সেটিংস অ্যাক্সেস করতে লগইন করুন",
    "account.username": "ব্যবহারকারীর নাম",
    "account.chooseDisplayName": "একটি প্রদর্শন নাম বেছে নিন",
    "account.email": "ইমেইল ঠিকানা",
    "account.managedByGoogle": "গুগল দ্বারা পরিচালিত",
    "account.saveUsername": "নাম সংরক্ষণ করুন",
    "account.saving": "সংরক্ষণ হচ্ছে...",
    "account.billing": "বিলিং",
    "account.manageBilling": "আপনার সাবস্ক্রিপশন এবং পেমেন্ট পদ্ধতি পরিচালনা করুন",
    "account.freePlan": "ফ্রি প্ল্যান",
    "account.basicAccess": "নেক্সাস ফিচারে বেসিক অ্যাক্সেস",
    "account.upgradePro": "প্রো তে আপগ্রেড করুন",
    "language.select": "ভাষা",
  },
  
  hi: {
    "app.title": "नेक्सस प्रो",
    "app.subtitle": "एंटरप्राइज थिंकिंग इंजन",
    "button.newSession": "नया सेशन",
    "button.login": "लॉगिन",
    "button.logout": "लॉगआउट",
    "menu.account": "अकाउंट",
    "menu.settings": "सेटिंग्स",
    "empty.greeting": "शुभ दोपहर, नेक्सस आपकी मदद के लिए यहाँ है",
    "empty.disclaimer": "नेक्सस गलतियाँ कर सकता है। कृपया महत्वपूर्ण जानकारी सत्यापित करें।",
    "input.placeholder": "नेक्सस को संदेश भेजें...",
    "input.webSearch": "कुछ भी पूछें - मैं वेब पर खोजूंगा...",
    "attach.camera": "कैमरा",
    "attach.photo": "फोटो",
    "attach.files": "फाइल्स",
    "attach.webSearch": "वेब सर्च",
    "attach.enabled": "सक्रिय",
    "attach.searchInternet": "इंटरनेट पर खोजें",
    "upload.uploading": "अपलोड हो रहा है...",
    "message.you": "आप",
    "message.ai": "नेक्सस AI",
    "message.thinking": "सोच रहा हूँ...",
    "message.thinkingProcess": "सोचने की प्रक्रिया",
    "message.readAloud": "जोर से पढ़ें",
    "message.stop": "रुकें",
    "message.generatedWith": "के साथ बनाया गया",
    "message.mode": "मोड",
    "voice.settings": "आवाज़ सेटिंग्स",
    "voice.voice": "आवाज़",
    "voice.speed": "गति",
    "webSearch.active": "वेब सर्च सक्रिय - नेक्सस इंटरनेट पर खोजेगा",
    "webSearch.on": "वेब सर्च चालू",
    "webSearch.off": "वेब सर्च",
    "sidebar.home": "होम",
    "sidebar.reasoningEngine": "रीजनिंग इंजन",
    "sidebar.preferences": "प्राथमिकताएं",
    "sidebar.account": "अकाउंट",
    "sidebar.settings": "सेटिंग्स",
    "sidebar.loginGoogle": "गूगल से लॉगिन करें",
    "sidebar.yourChats": "आपकी चैट्स",
    "sidebar.newChat": "नई चैट",
    "sidebar.noChats": "अभी तक कोई बातचीत नहीं",
    "sidebar.deleteChat": "हटाएं",
    "mode.whatIf": "क्या होता अगर",
    "mode.whatIfDesc": "काल्पनिक अन्वेषण",
    "mode.chainReaction": "चेन रिएक्शन",
    "mode.chainReactionDesc": "कारण विश्लेषण",
    "mode.parallelTimelines": "समानांतर टाइमलाइन",
    "mode.parallelTimelinesDesc": "विभिन्न परिणाम",
    "mode.active": "सक्रिय",
    "mode.selectMode": "रीजनिंग मोड चुनें",
    "account.title": "अकाउंट",
    "account.profileInfo": "प्रोफाइल जानकारी",
    "account.manageProfile": "अपनी प्रोफाइल और प्राथमिकताएं प्रबंधित करें",
    "account.notLoggedIn": "लॉगिन नहीं है",
    "account.loginToAccess": "अकाउंट सेटिंग्स एक्सेस करने के लिए लॉगिन करें",
    "account.username": "यूजरनेम",
    "account.chooseDisplayName": "एक डिस्प्ले नाम चुनें",
    "account.email": "ईमेल पता",
    "account.managedByGoogle": "गूगल द्वारा प्रबंधित",
    "account.saveUsername": "यूजरनेम सेव करें",
    "account.saving": "सेव हो रहा है...",
    "account.billing": "बिलिंग",
    "account.manageBilling": "अपनी सब्सक्रिप्शन और पेमेंट मेथड प्रबंधित करें",
    "account.freePlan": "फ्री प्लान",
    "account.basicAccess": "नेक्सस फीचर्स तक बेसिक एक्सेस",
    "account.upgradePro": "प्रो में अपग्रेड करें",
    "language.select": "भाषा",
  },
  
  ur: {
    "app.title": "نیکسس پرو",
    "app.subtitle": "انٹرپرائز تھنکنگ انجن",
    "button.newSession": "نیا سیشن",
    "button.login": "لاگ ان",
    "button.logout": "لاگ آؤٹ",
    "menu.account": "اکاؤنٹ",
    "menu.settings": "ترتیبات",
    "empty.greeting": "اچھی دوپہر، نیکسس آپ کی مدد کے لیے یہاں ہے",
    "empty.disclaimer": "نیکسس غلطیاں کر سکتا ہے۔ براہ کرم اہم معلومات کی تصدیق کریں۔",
    "input.placeholder": "نیکسس کو پیغام...",
    "input.webSearch": "کچھ بھی پوچھیں - میں ویب پر تلاش کروں گا...",
    "attach.camera": "کیمرہ",
    "attach.photo": "تصویر",
    "attach.files": "فائلز",
    "attach.webSearch": "ویب سرچ",
    "attach.enabled": "فعال",
    "attach.searchInternet": "انٹرنیٹ پر تلاش کریں",
    "upload.uploading": "اپلوڈ ہو رہا ہے...",
    "message.you": "آپ",
    "message.ai": "نیکسس AI",
    "message.thinking": "سوچ رہا ہوں...",
    "message.thinkingProcess": "سوچنے کا عمل",
    "message.readAloud": "بلند آواز میں پڑھیں",
    "message.stop": "رکیں",
    "message.generatedWith": "کے ساتھ بنایا گیا",
    "message.mode": "موڈ",
    "voice.settings": "آواز کی ترتیبات",
    "voice.voice": "آواز",
    "voice.speed": "رفتار",
    "webSearch.active": "ویب سرچ فعال - نیکسس انٹرنیٹ پر تلاش کرے گا",
    "webSearch.on": "ویب سرچ آن",
    "webSearch.off": "ویب سرچ",
    "sidebar.home": "ہوم",
    "sidebar.reasoningEngine": "ریزننگ انجن",
    "sidebar.preferences": "ترجیحات",
    "sidebar.account": "اکاؤنٹ",
    "sidebar.settings": "ترتیبات",
    "sidebar.loginGoogle": "گوگل سے لاگ ان کریں",
    "sidebar.yourChats": "آپ کی چیٹس",
    "sidebar.newChat": "نئی چیٹ",
    "sidebar.noChats": "ابھی تک کوئی گفتگو نہیں",
    "sidebar.deleteChat": "حذف کریں",
    "mode.whatIf": "اگر ہوتا تو",
    "mode.whatIfDesc": "فرضی تلاش",
    "mode.chainReaction": "چین ری ایکشن",
    "mode.chainReactionDesc": "سببی تجزیہ",
    "mode.parallelTimelines": "متوازی ٹائم لائنز",
    "mode.parallelTimelinesDesc": "مختلف نتائج",
    "mode.active": "فعال",
    "mode.selectMode": "ریزننگ موڈ منتخب کریں",
    "account.title": "اکاؤنٹ",
    "account.profileInfo": "پروفائل کی معلومات",
    "account.manageProfile": "اپنی پروفائل اور ترجیحات کا انتظام کریں",
    "account.notLoggedIn": "لاگ ان نہیں ہے",
    "account.loginToAccess": "اکاؤنٹ کی ترتیبات تک رسائی کے لیے لاگ ان کریں",
    "account.username": "یوزر نام",
    "account.chooseDisplayName": "ایک ڈسپلے نام منتخب کریں",
    "account.email": "ای میل پتہ",
    "account.managedByGoogle": "گوگل کے زیر انتظام",
    "account.saveUsername": "یوزر نام محفوظ کریں",
    "account.saving": "محفوظ ہو رہا ہے...",
    "account.billing": "بلنگ",
    "account.manageBilling": "اپنی سبسکرپشن اور ادائیگی کے طریقے منظم کریں",
    "account.freePlan": "مفت پلان",
    "account.basicAccess": "نیکسس فیچرز تک بنیادی رسائی",
    "account.upgradePro": "پرو میں اپ گریڈ کریں",
    "language.select": "زبان",
  },
  
  te: {
    "app.title": "నెక్సస్ ప్రో",
    "app.subtitle": "ఎంటర్‌ప్రైజ్ థింకింగ్ ఇంజన్",
    "button.newSession": "కొత్త సెషన్",
    "button.login": "లాగిన్",
    "button.logout": "లాగ్ అవుట్",
    "menu.account": "ఖాతా",
    "menu.settings": "సెట్టింగ్‌లు",
    "empty.greeting": "శుభ మధ్యాహ్నం, నెక్సస్ మీకు సహాయం చేయడానికి ఇక్కడ ఉంది",
    "empty.disclaimer": "నెక్సస్ తప్పులు చేయవచ్చు. దయచేసి ముఖ్యమైన సమాచారాన్ని ధృవీకరించండి.",
    "input.placeholder": "నెక్సస్‌కు సందేశం...",
    "input.webSearch": "ఏదైనా అడగండి - నేను వెబ్‌లో వెతుకుతాను...",
    "attach.camera": "కెమెరా",
    "attach.photo": "ఫోటో",
    "attach.files": "ఫైల్స్",
    "attach.webSearch": "వెబ్ సెర్చ్",
    "attach.enabled": "ఆన్",
    "attach.searchInternet": "ఇంటర్నెట్‌లో వెతకండి",
    "upload.uploading": "అప్‌లోడ్ అవుతోంది...",
    "message.you": "మీరు",
    "message.ai": "నెక్సస్ AI",
    "message.thinking": "ఆలోచిస్తున్నాను...",
    "message.thinkingProcess": "ఆలోచన ప్రక్రియ",
    "message.readAloud": "బిగ్గరగా చదవండి",
    "message.stop": "ఆపు",
    "message.generatedWith": "తో సృష్టించబడింది",
    "message.mode": "మోడ్",
    "voice.settings": "వాయిస్ సెట్టింగ్‌లు",
    "voice.voice": "వాయిస్",
    "voice.speed": "వేగం",
    "webSearch.active": "వెబ్ సెర్చ్ ఆన్ - నెక్సస్ ఇంటర్నెట్‌లో వెతుకుతుంది",
    "webSearch.on": "వెబ్ సెర్చ్ ఆన్",
    "webSearch.off": "వెబ్ సెర్చ్",
    "sidebar.home": "హోమ్",
    "sidebar.reasoningEngine": "రీజనింగ్ ఇంజన్",
    "sidebar.preferences": "ప్రాధాన్యతలు",
    "sidebar.account": "ఖాతా",
    "sidebar.settings": "సెట్టింగ్‌లు",
    "sidebar.loginGoogle": "గూగుల్‌తో లాగిన్",
    "sidebar.yourChats": "మీ చాట్స్",
    "sidebar.newChat": "కొత్త చాట్",
    "sidebar.noChats": "ఇంకా సంభాషణలు లేవు",
    "sidebar.deleteChat": "తొలగించు",
    "mode.whatIf": "ఏమిటి ఉంటే",
    "mode.whatIfDesc": "ఊహాజనిత అన్వేషణ",
    "mode.chainReaction": "చెయిన్ రియాక్షన్",
    "mode.chainReactionDesc": "కారణ విశ్లేషణ",
    "mode.parallelTimelines": "సమాంతర టైమ్‌లైన్స్",
    "mode.parallelTimelinesDesc": "వేర్వేరు ఫలితాలు",
    "mode.active": "యాక్టివ్",
    "mode.selectMode": "రీజనింగ్ మోడ్ ఎంచుకోండి",
    "account.title": "ఖాతా",
    "account.profileInfo": "ప్రొఫైల్ సమాచారం",
    "account.manageProfile": "మీ ప్రొఫైల్ మరియు ప్రాధాన్యతలను నిర్వహించండి",
    "account.notLoggedIn": "లాగిన్ కాలేదు",
    "account.loginToAccess": "ఖాతా సెట్టింగ్‌లను యాక్సెస్ చేయడానికి లాగిన్ అవ్వండి",
    "account.username": "వినియోగదారు పేరు",
    "account.chooseDisplayName": "ప్రదర్శన పేరును ఎంచుకోండి",
    "account.email": "ఇమెయిల్ చిరునామా",
    "account.managedByGoogle": "గూగుల్ ద్వారా నిర్వహించబడుతుంది",
    "account.saveUsername": "వినియోగదారు పేరు సేవ్ చేయండి",
    "account.saving": "సేవ్ అవుతోంది...",
    "account.billing": "బిల్లింగ్",
    "account.manageBilling": "మీ సబ్‌స్క్రిప్షన్ మరియు చెల్లింపు పద్ధతులను నిర్వహించండి",
    "account.freePlan": "ఉచిత ప్లాన్",
    "account.basicAccess": "నెక్సస్ ఫీచర్లకు బేసిక్ యాక్సెస్",
    "account.upgradePro": "ప్రోకు అప్‌గ్రేడ్ చేయండి",
    "language.select": "భాష",
  },
  
  fr: {
    "app.title": "Nexus Pro",
    "app.subtitle": "Moteur de Réflexion Entreprise",
    "button.newSession": "Nouvelle Session",
    "button.login": "Connexion",
    "button.logout": "Déconnexion",
    "menu.account": "Compte",
    "menu.settings": "Paramètres",
    "empty.greeting": "Bon après-midi, Nexus est là pour vous aider",
    "empty.disclaimer": "Nexus peut faire des erreurs. Veuillez vérifier les informations critiques.",
    "input.placeholder": "Message à Nexus...",
    "input.webSearch": "Demandez n'importe quoi - Je chercherai sur le web...",
    "attach.camera": "Caméra",
    "attach.photo": "Photo",
    "attach.files": "Fichiers",
    "attach.webSearch": "Recherche Web",
    "attach.enabled": "Activé",
    "attach.searchInternet": "Rechercher sur internet",
    "upload.uploading": "Téléchargement...",
    "message.you": "Vous",
    "message.ai": "Nexus IA",
    "message.thinking": "Réflexion...",
    "message.thinkingProcess": "Processus de Réflexion",
    "message.readAloud": "Lire à Voix Haute",
    "message.stop": "Arrêter",
    "message.generatedWith": "Généré avec",
    "message.mode": "mode",
    "voice.settings": "Paramètres Vocaux",
    "voice.voice": "Voix",
    "voice.speed": "Vitesse",
    "webSearch.active": "Recherche Web Active - Nexus cherchera sur internet",
    "webSearch.on": "Recherche Web ON",
    "webSearch.off": "Recherche Web",
    "sidebar.home": "Accueil",
    "sidebar.reasoningEngine": "Moteur de Raisonnement",
    "sidebar.preferences": "Préférences",
    "sidebar.account": "Compte",
    "sidebar.settings": "Paramètres",
    "sidebar.loginGoogle": "Connexion avec Google",
    "sidebar.yourChats": "Vos Chats",
    "sidebar.newChat": "Nouveau Chat",
    "sidebar.noChats": "Pas encore de conversations",
    "sidebar.deleteChat": "Supprimer",
    "mode.whatIf": "Et Si",
    "mode.whatIfDesc": "Exploration hypothétique",
    "mode.chainReaction": "Réaction en Chaîne",
    "mode.chainReactionDesc": "Analyse causale",
    "mode.parallelTimelines": "Lignes de Temps Parallèles",
    "mode.parallelTimelinesDesc": "Résultats divergents",
    "mode.active": "Actif",
    "mode.selectMode": "Sélectionner le mode de raisonnement",
    "account.title": "Compte",
    "account.profileInfo": "Informations du Profil",
    "account.manageProfile": "Gérez votre profil et vos préférences",
    "account.notLoggedIn": "Non connecté",
    "account.loginToAccess": "Connectez-vous pour accéder aux paramètres",
    "account.username": "Nom d'utilisateur",
    "account.chooseDisplayName": "Choisissez un nom d'affichage",
    "account.email": "Adresse Email",
    "account.managedByGoogle": "Géré par Google",
    "account.saveUsername": "Enregistrer le Nom",
    "account.saving": "Enregistrement...",
    "account.billing": "Facturation",
    "account.manageBilling": "Gérez votre abonnement et modes de paiement",
    "account.freePlan": "Plan Gratuit",
    "account.basicAccess": "Accès basique aux fonctionnalités Nexus",
    "account.upgradePro": "Passer à Pro",
    "language.select": "Langue",
  },
};

const languageNames: Record<Language, string> = {
  en: "English",
  es: "Español",
  de: "Deutsch",
  bn: "বাংলা",
  hi: "हिंदी",
  ur: "اردو",
  te: "తెలుగు",
  fr: "Français",
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    if (typeof window !== "undefined") {
      const saved = localStorage.getItem("nexus-language");
      return (saved as Language) || "en";
    }
    return "en";
  });

  useEffect(() => {
    localStorage.setItem("nexus-language", language);
  }, [language]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || translations.en[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}

export { languageNames };
